.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "SPHIA" "1" "October 2013" "" ""
.
.SH "NAME"
\fBsphia\fR \-\- Command line utility for sophia databases
.
.SH "SYNOPSIS"
\fBsphia\fR <command> [\-\-key <key>] [\-\-value <value>] [\-\-path <path>]
                [\-\-version] [\-\-help]
.
.SH "OPTIONS"
  \-V, \-\-version
      output program version
.
.P
  \-h, \-\-help
      output help information
.
.P
  \-\-verbose
      enable verbose output
.
.P
  \-p, \-\-path <path>
      set the path
.
.P
  \-k, \-\-key <name>
      key to get
.
.P
  \-v, \-\-value <name>
      value to set
.
.P
  \-s, \-\-strict
      enable strict mode for a command
.
.SH "COMMANDS"
  \fBinit\fR
      initialize a new database
.
.P
  \fBget\fR
      get a value by key
.
.P
  \fBset\fR
      set a value by key
.
.P
  \fBrm|remove\fR
      remove a value by key
.
.P
  \fBls|list\fR
      list all keys and values
.
.P
  \fBclear\fR
      clears database of all keys
.
.P
  \fBpurge\fR
      purge database of all corrupt and incomplete data
.
.P
  \fBreset\fR
      reset database of all data
.
.P
  \fBcount\fR
      get the count
.
.P
  \fBsearch\fR
      search for a key or value      
.
.SH "AUTHOR"
.
.IP "\(bu" 4
Joseph Werle \fIjoseph\.werle@gmail\.com\fR
.
.IP "" 0
.
.SH "REPORTING BUGS"
.
.IP "\(bu" 4
\fIhttps://github\.com/jwerle/sphia/issues\fR
.
.IP "" 0
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
\fIhttps://github\.com/jwerle/sphia\fR
.
.IP "\(bu" 4
\fIhttp://sphia\.org\fR
.
.IP "" 0
.
.SH "LICENSE"
MIT