.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "SPHIA" "1" "October 2013" "" ""
.
.SH "NAME"
\fBsphia\fR \-\- Command line utility for sophia databases
.
.SH "SYNOPSIS"
\fBsphia\fR <command> [\-\-key <key>] [\-\-value <value>] [\-\-path <path>]
                [\-\-version] [\-\-help]
.
.SH "OPTIONS"
  \-V, \-\-version                 output program version
  \-h, \-\-help                    output help information
  \-V, \-\-verbose                 enable verbose output
  \-p, \-\-path <path>             set the path
  \-k, \-\-key <name>              key to get
  \-v, \-\-value <name>            value to set
.
.SH "COMMANDS"
   init                         initialize a new database
   get \-k <key>                 get a value by key
   set \-k <key> \-v <value>      set a value by key
   ls                           list all keys and values
   clear                        clears database of all keys
.
.SH "AUTHOR"
.
.IP "\(bu" 4
Joseph Werle \fIjoseph\.werle@gmail\.com\fR
.
.IP "" 0
.
.SH "REPORTING BUGS"
.
.IP "\(bu" 4
\fIhttps://github\.com/jwerle/sphia/issues\fR
.
.IP "" 0
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
\fIhttps://github\.com/jwerle/sphia\fR
.
.IP "\(bu" 4
\fIhttp://sphia\.org\fR
.
.IP "" 0
.
.SH "LICENSE"
MIT