#!/bin/bash

TESTS=`find test/* -type f -perm +111`
EXIT_CODE=0

echo
echo "Running sphia tests"
for t in $TESTS; do
  ./$t
  if [ $? -ne 0 ]; then
    echo "  (✖) $t"
    EXIT_CODE=1
  else
    echo "  (✓) $t"
  fi
done

exit $EXIT_CODE
